# Generated by Django 5.1.7 on 2025-03-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labels", "0001_initial"),
        ("tasks", "0004_auto_20250314_1453"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="point",
        ),
        migrations.AddField(
            model_name="task",
            name="label",
            field=models.ManyToManyField(
                blank=True,
                max_length=255,
                null=True,
                to="labels.label",
                verbose_name="Метка",
            ),
        ),
    ]
