# Generated by Django 5.1.7 on 2025-03-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0006_alter_task_worker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='worker',
            new_name='executor',
        ),
        migrations.AlterField(
            model_name='task',
            name='label',
            field=models.ManyToManyField(blank=True, null=True, to='labels.label', verbose_name='Метка'),
        ),
    ]
